### ISSUE TITLE
Additional setup of DA

### ISSUE THREAD

**Issue by albertovitto** [boschresearch/one-shot-synthesis#1]
Hi,
I'm having troubles with the enviroment setup in Windows 10: after creating the enviroment with `conda env create --file environment.yml`, I don't understand how to integrate the additional packages from _StyleGAN2-ADA_ repository.
Could you please help me? Thank you very much!

**Comment by SushkoVadim** [comment]
Hi, my notifications were not set up properly, sorry for the long replying!

We unfortunately could not release this part of the implementation due to licensing. 

As a replacement for DA from *StyleGAN2-ADA* repository, we provide our own minimal implementation of DA [here](https://github.com/boschresearch/one-shot-synthesis/blob/master/core/differentiable_augmentation/AugmentPipe_kornia.py)
(the AugmentPipe_kornia class).
You can use this code by running training with the `--use_kornia_augm` flag.
In principle, this should be already enough to reproduce the full functionality of the model.

Although, as this replacement achieves a bit lower performance and works slower than the official implementation from *StyleGAN2-ADA*, we recommend set up the Augmentation Pipeline based on the example from https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/training/augment.py
(the AugmentPipe class).
For this, a user needs to create a separate class `AugmentPipe` on the basis of [this class](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/6f160b3d22b8b178ebe533a50d4d5e63aedba21d/training/augment.py#L117). 
Then, this pipeline should be referenced instead of [AugmentPipeKornia](https://github.com/boschresearch/one-shot-synthesis/blob/b90839457a399cffc13f164d0596976a883047d5/core/differentiable_augmentation/AugmentPipe_kornia.py#L8) in our code, by being called [here](https://github.com/boschresearch/one-shot-synthesis/blob/b90839457a399cffc13f164d0596976a883047d5/core/differentiable_augmentation/diff_augm.py#L9).

Overall, this should be a rather straightforward transfer of the class `AugmentPipe` to our codebase. Please note that for a proper compiling, the DA code requires transferring some more helping files from the *StyleGAN2-ADA* repository , while the python environment may also require some additional installations. One well-known issue arising during additional installations is discussed [here](https://github.com/NVlabs/stylegan2-ada-pytorch/issues/2).

I hope this short instruction helps to incorporate this part of the model into codebase.
Feel free to ask for more details

Regards,
Vadim

**Comment by Bananaspirit** [comment]
@SushkoVadim I added the class according to your instructions, while running with DA stylegan2-ada I received the following error. Any ideas on how to fix it?
```sh
Traceback (most recent call last):
  File "/work/one-shot-synthesis/train.py", line 33, in <module>
    out_G = diff_augment(out_G)
  File "/work/one-shot-synthesis/core/differentiable_augmentation/diff_augm.py", line 13, in __call__
    return self.augment_func(batch)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/one-shot-synthesis/core/differentiable_augmentation/AugmentPipe.py", line 161, in forward
    assert isinstance(images, torch.Tensor) and images.ndim == 4
AssertionError
```
